version: '3.2'

networks:
  net:
    name: temboard-net
    driver: bridge

volumes:
  # Monitor
  ssl:
    name: temboard-ssl
    driver: local
  pgdata:
    name: temboard-pgdata
    driver: local
  home:
    name: temboard-home
    driver: local  

services:
  # Monitor
  temboard:
    container_name: temboard
    hostname: temboard
    image: temboard:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TEMBOARD_VERSION: "8.2.1"
      target: temboard
    networks:
      - net
    restart: always
    volumes:
      - ssl:/etc/ssl/certs
      - pgdata:/var/lib/postgresql/data
      - home:/home/temboard
      - ./Temboard/temboard.conf:/home/temboard/temboard.conf:rw
    ports:
      - 3010:8888
      - 3110:5432
    cpus: 1
    mem_limit: 2GB
    shm_size: 256mb
    command: > 
      postgres
      -c max_connections=50
      -c shared_buffers=256MB
      -c effective_cache_size=768MB
      -c maintenance_work_mem=128MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=7864kB
      -c default_statistics_target=500
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c work_mem=1310kB
      -c huge_pages=off
      -c min_wal_size=512MB
      -c max_wal_size=1GB
      -c autovacuum=off
      -c max_worker_processes=2
      -c max_parallel_workers_per_gather=2
      -c max_parallel_workers=2
      -c max_parallel_maintenance_workers=2
      -c log_destination='stderr'
      -c logging_collector=on
      -c log_directory='/var/lib/postgresql/data/log'
      -c log_filename='postgresql.log'
      -c log_min_messages='warning'
      -c log_min_error_statement='error'
      -c log_min_duration_statement='0'
      -c log_duration=on
      -c log_line_prefix='%t [%p]: [%l-1] db=%d,user=%u,app=%a,client=%h %q '
      -c log_lock_waits=on
      -c log_statement='none'
      -c log_timezone='America/Bahia' 
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"